#!/usr/bin/env php
<?php

use F3\Changelog\Changelog;
use F3\Changelog\Config;

(function () {
    foreach (
        [
            '/../../autoload.php',
            '/../vendor/autoload.php',
            '/vendor/autoload.php',
        ] as $path
    ) {
        $autoload = __DIR__ . $path;
        if (file_exists($autoload)) {
            require_once $autoload;
            return;
        }
    }
    fwrite(STDERR, 'Composer autoload not found.' . PHP_EOL);
    die(1);
})();


$changelog = Changelog::fromConfig(Config::fromJsonFile('.changelog.json'))
    ->generateForVersion($argv[1] ?? null);

echo "\n$changelog\n\n";
