#!/usr/bin/env php
<?php
use F3\Changelog\Cli\{
    Application, ArgvInput, StdOutput
};

(function () {
    foreach (
        [
            '/../../autoload.php',
            '/../vendor/autoload.php',
            '/vendor/autoload.php',
        ] as $path
    ) {
        $autoload = __DIR__ . $path;
        if (file_exists($autoload)) {
            require_once $autoload;
            return;
        }
    }
    fwrite(STDERR, 'Composer autoload not found.' . PHP_EOL);
    die(1);
})();

Application::build()->run(new ArgvInput($argv), new StdOutput());
