#!/usr/bin/env php
<?php
use F3\Changelog\Cli\{
    Application, ArgvInput, Config, StdOutput
};
use F3\Changelog\Generator;
use F3\Changelog\Git\{
    RepoDetector, Shell, ShellGit
};

(function () {
    foreach (
        [
            '/../../autoload.php',
            '/../vendor/autoload.php',
            '/vendor/autoload.php',
        ] as $path
    ) {
        $autoload = __DIR__ . $path;
        if (file_exists($autoload)) {
            require_once $autoload;
            return;
        }
    }
    fwrite(STDERR, 'Composer autoload not found.' . PHP_EOL);
    die(1);
})();

(new Application(
    new Generator(
        new ShellGit(Config::fromJsonFile('.release-notes.json')['remote'],
            new Shell(),
            new RepoDetector()
        )
    )
))->run(new ArgvInput($argv), new StdOutput());
